#! /usr/bin/env python


"""
A bit of code to set the srm protocol for T1_US_FNAL_Tape_Test.
"""

from __future__ import division, print_function

import pprint

from rucio.client.client import Client

token = None

tfc = [
    {'path': '^/+lustre/unmerged/logs/prod/(.*)', 'out': 'srm://cmslmon.fnal.gov:8443/srm/v2/server?SFN=/lustre/unmerged/logs/prod/$1', 'proto': 'srmv2'},
    {'path': '^/+store/(.*)', 'out': 'srm://cmsdcatape01.fnal.gov:8443/srm/managerv2?SFN=/11/store/test/rucio/int/cms/store/$1', 'proto': 'srmv2'},
    {'path': '^/+store/(.*)', 'out': 'srm://cmsdcatape01.fnal.gov:8443/srm/managerv2?SFN=$1', 'chain': 'direct', 'proto': 'srmv2'} 
]

proto = {
    'scheme': 'srm',
    'hostname': 'cmsdcatape01.fnal.gov',
    'port': 8443,
    'extended_attributes': {},
    'domains': {'wan' : {'read': 1, 'write': 1, 'third_party_copy': 1, 'delete': 1}, 'lan': {'read': 0, 'write': 0, 'delete': 0}}
}

#proto['impl'] = 'rucio.rse.protocols.gfalv2.Default'

proto['extended_attributes']['web_service_path'] = '/srm/managerv2?SFN='

proto['prefix'] = '/'
proto['extended_attributes']['tfc_proto'] = 'srmv2'
proto['extended_attributes']['tfc'] = tfc

if token:
    proto['extended_attributes']['space_token'] = token

if proto['extended_attributes'] == {}:
    proto['extended_attributes'] = None

proto['impl'] = 'rucio.rse.protocols.gfal.Default'

pprint.pprint(proto)
client = Client()
client.whoami()

client.add_protocol(rse='T1_US_FNAL_Tape_Test', params=proto)

